### PR TITLE
Replace `ThreadLocalRandom` with a `L64X128MixRandom` `RandomGenerator`

### LINKED ISSUE #23: Solid block rotation glitch
[1.20.1, Fabric]
Hey, 
Since the 2.0.0 version, there's this weird visual glitch where after you update (destroy/place on) a solid block, solid blocks around it in a small radius change their rotation(?) randomly. Some blocks are non-rotatable but they still somehow do. It doesn't affect transparent/foliage blocks like grass or leaves.
I don't know whether that's a standalone or incompatibility issue, since i didn't really test it out in vanilla environment. I've only managed to figure out that with FR disabled this doesn't happen, maybe it's some other mod acting funny.

https://github.com/AnOpenSauceDev/FastRandom/assets/150455861/ebdc1d85-25e7-4e22-b721-8733d940de9c

### LINKED ISSUE #26: Enchantment Unpredictability
This mod is causing enchanting to become highly unpredictable and random, causing the table to roll infinitely without actually holding anything, so it's like gambling / rolling the dice with what you're going to get.

### PR DESCRIPTION
**Pull request by Steveplays28**
This improves performance by 2x, using `L64X128MixRandom`, compared to vanilla.
Also fixed stuck object rendering, such as arrows, displaying inconsistently. Alongside fixes for enchantment and world generation inconsistencies.

- Closes #23
- Closes #26

### CODE REVIEW

**Comment by AnOpenSauceDev** [comment]
For some reason, I encountered some very unusual spawn behaviour where I was spawned at around y=0 in a mineshaft, but I couldn't get this to occur again.

**Comment by AnOpenSauceDev** [comment]
Dropped itemstacks with more than 2 of the same item have some jitter. This does not occur with singular dropped items, and seems to happen at _random_ intervals.

**Comment by Steveplays28** [comment]
Seems like thunder is also broken, because the random int used for it never is `0`.

**Comment by Steveplays28** [comment]
Just pushed a fix for item rendering.

**Comment by AnOpenSauceDev** [comment]
The items work fine now, but I just discovered that mineshaft generation is very... chaotic, and seemingly infinite? What's happening is that tonnes of mineshafts are generating next to each other, completely ignoring the structure rules (and greatly reducing chunk generation performance for me). This also affects Badlands Mineshaft generation as well. No other structures are affected.

**Comment by Steveplays28** [comment]
Alright, I'll take a look!

**Comment by Steveplays28** [comment]
I think I'll add a new implementation of Minecraft's `Random` interface for cases where it breaks. That way we can just inject that class into the start of broken methods, replacing the faster random class.

**Comment by Steveplays28** [comment]
Hi @AnOpenSauceDev, could you check if the latest commit works without issues for you as well?
Mineshafts shouldn't generate everywhere anymore, visual issues should be fixed, and enchantments should be predictable again.

I haven't done any benchmarking yet, could you check how this performs, compared to vanilla, on your system?
I'll do some testing as well when I have time.

**Comment by AnOpenSauceDev** [comment]
Just tried your new commit out, and for some reason the block rotation and item shuffling has returned, and enchantments still seem to be inaccurate. Structures do generate properly again. Not sure if something has gone wrong on my end though.

**Comment by Steveplays28** [comment]
Ah, you're right. Also happens on my end now. Weird that it didn't happen for me yesterday.

**Comment by Steveplays28** [comment]
I believe I've found a fix that actually works now. It's not as clean as I'd like it to be, since it involves effectively replacing classes, but at least it might work as it should.

My benchmark results seem to be slower than vanilla though?
```java
// Benchmark
		var nanoTimeRandomGeneratorRandomStart = System.nanoTime();
		var randomGeneratorRandom = new RandomGeneratorRandom(RandomSeed.getSeed());
		for (int i = 0; i < 100000; i++) {
			randomGeneratorRandom.nextInt();
			randomGeneratorRandom.nextLong();
			randomGeneratorRandom.nextDouble();
			randomGeneratorRandom.nextFloat();
			randomGeneratorRandom.nextBoolean();
			randomGeneratorRandom.nextGaussian();
		}
		var nanoTimeRandomGeneratorRandomEstimated = System.nanoTime() - nanoTimeRandomGeneratorRandomStart;

		var nanoTimeVanillaStart = System.nanoTime();
		var vanillaRandom = new CheckedRandom(RandomSeed.getSeed());
		for (int i = 0; i < 100000; i++) {
			vanillaRandom.nextInt();
			vanillaRandom.nextLong();
			vanillaRandom.nextDouble();
			vanillaRandom.nextFloat();
			vanillaRandom.nextBoolean();
			vanillaRandom.nextGaussian();
		}
		var nanoTimeVanillaEstimated = System.nanoTime() - nanoTimeVanillaStart;

		LOGGER.info("RandomGeneratorRandom: {}s, vanilla: {}s", nanoTimeRandomGeneratorRandomEstimated / 1e9,
				nanoTimeVanillaEstimated / 1e9
		);
```
With `L128X128MixRandom`, this returns `RandomGeneratorRandom: 0.0229267s, vanilla: 0.0173085s`.

It's supposed to be 4x faster than vanilla though.

**Comment by AnOpenSauceDev** [comment]
> With `L128X128MixRandom`, this returns `RandomGeneratorRandom: 0.0229267s, vanilla: 0.0173085s`. It's supposed to be 4x faster than vanilla (`CheckedRandom`). Is my benchmarking code bad?

It could be that one or more random functions are much slower compared to vanilla, so it would be better to benchmark every method separately, instead of doing it all at once.

**Comment by AnOpenSauceDev** [comment]
Odd, the new generator is consistently slower vs. vanilla.

```java
# int
RandomGeneratorRandom: 0.019367281s, vanilla: 0.007450953s

# long
RandomGeneratorRandom: 0.025516993s, vanilla: 0.012274628s

# double
RandomGeneratorRandom: 0.023700025s, vanilla: 0.010885982s

# float
RandomGeneratorRandom: 0.022416038s, vanilla: 0.00581613s

# bool
RandomGeneratorRandom: 0.019014472s, vanilla: 0.006581874s

# guassian
RandomGeneratorRandom: 0.023590226s, vanilla: 0.023925273s
```

**Comment by Steveplays28** [comment]
huh. This keeps getting weirder.
I'll ask around in the Fabric Discord server.

**Comment by AnOpenSauceDev** [comment]
@Steveplays28 Actually, I found a fix, you were accidentally using `L128x128MixRandom`, which was significantly slower than `L64X128MixRandom`. After doing that, I got roughly 2x the performance compared to vanilla.

**Comment by Steveplays28** [comment]
Oh, nice! Great that you found the issue.
Is everything working correctly on your end as well, in terms of all the issues that were present before?

**Comment by AnOpenSauceDev** [comment]
Yep! Everything works correctly.

**Comment by Steveplays28** [comment]
Nice! One last thing I could do then, is test if replacing some `new CheckedRandom(seed)` calls would work.
In the world generator, there's quite a few of these instantiations. Might help with gaussian-related functions.

If it does break stuff though, we can always choose not to include it.
Is terrain generation currently consistent?

**Comment by AnOpenSauceDev** [comment]
I'll test it out now, but at a glance worldgen looks like vanilla.

**Comment by AnOpenSauceDev** [comment]
Can confirm that worldgen is 1:1 when using the same seed.

**Comment by Steveplays28** [comment]
Awesome! That's great progress.
Do you want to try replacing calls in the world generator? Could do that in a followup PR, alongside another followup PR for a docs update.

I'll mark the PR as ready for review, if you don't haven't found any other issues.

**Review by AnOpenSauceDev — APPROVED** [review]
I tried out a handful of random events, and they all are behaving correctly. I'll merge this.

**Comment by AnOpenSauceDev** [comment]
> This improves performance by 2x

Just wrote up [a benchmark](https://github.com/AnOpenSauceDev/FastRandom/blob/master/src/main/java/com/github/anopensaucedev/fasterrandom/RandBench.java), it's actually anywhere from 4x -> 8x faster, depending on the generator used.

 The new benchmark also a bit more detailed, and only executes on dev.

**Pull request merged**
