### PR TITLE
Fix `nextLong()`

### PR DESCRIPTION
**Pull request by Steveplays28**
- `nextLong()` now calls `randomGenerator.nextLong()` instead of `randomGenerator.nextInt()`, fixing BetterX compatibility and making vanilla parity 1:1 (except for the MC-239059 fix)
- Changed the logging messages to reflect these parity fixes
- Moved some classes around into their own packages, to clean up the main package
- Renamed the benchmarking class and cleaned up naming
- Moved the legacy benchmark into the benchmarking class
- Uncommented benchmarking in development environments
- Added JavaDocs to the benchmarking class

Thanks to unilock for spotting the issue with `RandomGeneratorRandom#nextLong`, see #41.

### CODE REVIEW

**Review by AnOpenSauceDev — APPROVED** [review]
Everything works, LTGM!

Also, you should be able to delete those branches now.

**Comment by Steveplays28** [comment]
Awesome, thanks.

**Comment by unilock** [comment]
Does just using `nextLong` instead of `nextInt` really fix the BetterX issue? I thought that was due to `nextSplitter` creating a `CheckedRandom$Splitter` instance instead of a `Splitter` based on `RandomGeneratorRandom`.

**Comment by AnOpenSauceDev** [comment]
That's what I thought in #34, but `nextLong` being swapped around fixed BetterX instantly.

**Pull request merged**
